name: build and test
on: 
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  ros_ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-22.04
        ros_distribution: 
          - humble
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros2_ws/src
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src
      
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: |
            cpp_test
            
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      
    
